# Generated by Django 4.1.3 on 2022-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("image_url", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "link",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("reply_count", models.IntegerField()),
                ("up_count", models.IntegerField()),
            ],
        ),
    ]
