# Generated by Django 4.1.3 on 2022-11-08 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hotdeal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
